name: 'MayMeow's Hugo build action'
author: 'May Meow'
description: 'Action to build hugo websites'
branding:
  icon: 'cloud-snow'
  color: 'purple'
inputs: 
  production-config:
    description: 'Path to production config file, if not provided it will be used default value'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.production-config }}
